---
safe: true
exclude: ['_presite_plugins', 'README.md']
title: Devnexus 2022
timezone: UTC
active-header: navigation.html
cfp-is-open: false
registration: open
collections:
  speakers:
    title: Speakers 2022
    output: true
    permalink: /:collection/:path
  events:
     title: Presentations 2022
     output: true
     permalink: /presentations/:path/
  event-instructions:
     title: Workshop Prep 2022
     output: true
     permalink: /presentations/:path/instructions
  tracks:
    title: Tracks
    output: false
  organizers:
    title: Organizers
    output: true
    permalink: /:collection/:path
email: info@ajug.org
description: Largest Java Conference in the USA.
baseurl:
url:
uploads_dir: "/uploads"
links:
   cfp: https://cfp.connectevents.io/en/dn2022/cfp/session/new 
   register: https://reg.connectevents.io/ConnectEvents/devnexus2022/
   announcements: https://twitter.com/devnexus
   recordings: https://www.recallact.com/ajug
   reg_maillist: https://ajug.us7.list-manage.com/subscribe/post?u=0b3b17489713c9e7c62595dd3&amp;id=51e5b6d965
twitter_card:
  default_image: https://devnexus.com/assets/img/dev.001.jpeg
  type: summary
  site: "@devnexus"
  creator:  "@atlantajug"
markdown: kramdown
theme:
_editor:
  default_path: /about/
defaults:
  - scope:
      path: "archive"
    values:
      layout: "archive"
  - scope:
     path: ""
     type: "event-instructions"
    values:
     layout: "workshop_instructions"
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "assets/img/sponsors"
    values:
      sponsor: true
_options:
  logo_image:
    width: 360
    height: 360
    resize_style: "cover"
    expandable: false
    uploads_dir: /assets/img/sponsors/
_defaults:
  logo_image: "/assets/img/sponsor.png"
