---
safe: true
exclude: ['_presite_plugins', 'README.md', '_move_to_arhcive.html']
title: Devnexus 2024
timezone: UTC
active-header: navigation-before-schedule.html
cfp-is-open: false
registration:
  text: REGISTER TODAY!
  status: enabled
feedback: NOTshow
collections:
  speakers:
    title: Speakers 2024
    output: true
    permalink: /:collection/:slug
  events:
     title: Presentations 2024
     output: true
     permalink: /presentations/:slug/
  event-instructions:
     title: Workshop Prep 2024
     output: true
     permalink: /presentations/:path/instructions
  tracks:
    title: Tracks
    output: false
  organizers:
    title: Organizers
    output: true
    permalink: /:collection/:path
email: info@ajug.org
description: The longest-running and Largest Java Ecosystem Conference in the World.
baseurl:
url:
uploads_dir: "/uploads"
links:
   stay-informed: https://mailchi.mp/4481d4c86d3b/devnexus-site-signup
   hotel-block: https://www.marriott.com/event-reservations/reservation-link.mi?id=1698079884809&key=GRP&app=resvlink
   cfp: https://sessionize.com/devnexus-2024/
   register: https://reg.connectevents.io/ConnectEvents/devnexus2024/
   signIn: https://reg.connectevents./ConnectEvents/devnexus2024/
   announcements: https://mailchi.mp/4481d4c86d3b/devnexus-site-signup
   recordings: https://www.recallact.com/ajug
   reg_maillist: https://mailchi.mp/4481d4c86d3b/devnexus-site-signup
twitter_card:
  default_image: https://devnexus.com/assets/img/twittercard.png
  type: summary
  site: "@devnexus"
  creator:  "@atlantajug"
markdown: kramdown
theme:
plugins:
  - jekyll-seo-tag
_editor:
  default_path: /about/
defaults:
  - scope:
      path: "archive"
    values:
      layout: "archive"
  - scope:
     path: ""
     type: "event-instructions"
    values:
     layout: "workshop_instructions"
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "assets/img/sponsors"
    values: 
      sponsor: true
  - scope:
       path: ""
       type: "events"
    values:
      layout: "preso_details" 
  - scope:
       path: ""
       type: "speakers"
    values:
      layout: "speaker_bio"        
_options:
  logo_image:
    width: 300
    height: 300
    resize_style: "cover"
    expandable: false
    uploads_dir: /assets/img/sponsors/
_defaults:
  logo_image: "/assets/img/sponsor.png"
