server:
  port: 8090
  servlet-path: /
  session:
    timeout: 1200
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  ssl:
    enabled: false
multipart:
  enabled: true
  max-file-size: 5Mb
  max-request-size: 10Mb
security:
  enable-csrf: false
devnexus:
  csv:
    date-format: MM/dd/yyyy
  twitter:
    enabled: false
    oauth:
      consumerKey:
      consumerSecret:
      accessToken:
      accessTokenSecret:
  amazon:
    awsAccessKeyId:
    awsSecretKey:
  mail:
    emailProvider: none # none | smtp | sendgrid | amazon_ses
    sendgrid-api-key:
    authenticationEnabled: false
    debugEnabled: false
    user:
      id:
      password:
      from: info@ajug.org
      cc:
    smtp:
      port: 25
      host: localhost
  recaptcha:
    enabled: false
    publicKey:
    privateKey:
  registration:
    state: open # open | closed | soldout | hide
  cfp:
    state: open # open | closed
spring:
  datasource:
    url: jdbc:h2:mem:devnexus_demo
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    open-in-view: false
    properties:
      dialect: com.devnexus.ting.core.hibernate.ImprovedH2Dialect
      show_sql: false
      generate_ddl: validate

TING_CLIENT_ID: fillme
TING_CLIENT_SECRET: fillme
TING_PUSH_URL: fillme
TING_PUSH_APP_ID: fillme
TING_PUSH_MASTER_SECRET: fillme

#paypal
PAYPAL_ACCOUNT: payments-facilitator@ajug.org
PAYPAL_ENDPOINT: api.sandbox.paypal.com
PAYPAL_CLIENT_ID: xxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxx_xxxxxxxxxx
PAYPAL_CLIENT_SECRET: xxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxx_xxxxxxxxxx